"""
MCLPSO: Multi-swarm Comprehensive Learning Particle Swarm Optimisation
for Multilevel Intensity Partitioning of Brain MRI Images

Implementation based on:
  Liang, J.J., Qin, A.K., Suganthan, P.N. & Baskar, S.
  "Comprehensive Learning Particle Swarm Optimizer for Global Optimisation
  of Multimodal Functions."  IEEE Trans. Evol. Comput., 10(3), 2006.

Applied to MRI segmentation with the same 2D Renyi entropy objective as
the HyPSO implementation in hypso_mri_segmentation.py.

Algorithm overview
------------------
MCLPSO replaces the standard social learning term (pulling a particle
toward the *single* global best) with a **comprehensive learning** strategy:
  - For each dimension d of particle i, an independent exemplar f_i(d) is
    selected probabilistically from the personal-best archive.
  - With probability pc[i], dimension d learns from a randomly chosen
    competitor's personal best; otherwise it continues to use its own.
  - If a particle fails to improve its personal best for *m* consecutive
    iterations (the "refresh gap"), it is refreshed with a randomised
    exemplar constructed by tournament selection from the personal bests.
  - This prevents premature convergence in multimodal fitness landscapes.

Key hyperparameters (following the paper)
------------------------------------------
  N      = 50            Swarm size
  FE_max = 10,000 * D   Max function evaluations  (D = number of thresholds)
  w      = 0.729         Inertia weight
  c      = 1.494         Acceleration coefficient  (single coefficient)
  pc     in [0.05, 0.5]  Learning probability per particle
                         (linearly spaced across the swarm)
  m      = 7             Refresh gap (stagnation limit in iterations)
  q      = 0.5           Renyi order parameter

Relationship to HyPSO
----------------------
Both algorithms share:
  * The same objective: 2D Renyi entropy on the joint histogram of the
    original image and its nonlocal-means-filtered version.
  * The same preprocessing, joint-histogram, and entropy routines (imported
    from hypso_mri_segmentation).
  * The same segmentation pipeline structure.

MCLPSO differs from HyPSO in that it uses no meta-level hyper-heuristic or
hill-climbing local search; all diversity is generated by the comprehensive
learning strategy and the refresh mechanism.
"""

from __future__ import annotations

import random
from typing import List, Optional, Tuple

import numpy as np

# ---------------------------------------------------------------------------
# Re-use shared building blocks from the HyPSO module
# ---------------------------------------------------------------------------
from hypso_mri_segmentation import (
    _NBINS,
    nonlocal_means_filter,
    build_joint_histogram,
    compute_2d_renyi_entropy,
    compute_ssim,
)


# ===========================================================================
# 1.  PARTICLE
# ===========================================================================

def _random_threshold_vector(D: int) -> np.ndarray:
    """Sample a random sorted threshold vector of dimension D."""
    t = np.random.randint(1, 255, size=D)
    return np.sort(t)


def _clamp_and_sort(position: np.ndarray) -> np.ndarray:
    """Clamp threshold values to [1, 254] and sort to maintain ordering."""
    return np.sort(np.clip(np.round(position).astype(int), 1, 254))


class CLParticle:
    """Single MCLPSO particle.

    Attributes
    ----------
    position          : current threshold vector
    velocity          : current velocity vector
    personal_best     : best position found by this particle
    personal_best_fitness : fitness of personal_best
    exemplar          : the composite exemplar f_i (one pbest per dimension)
    stagnation        : consecutive iterations without a personal-best update
    """

    def __init__(self, D: int) -> None:
        self.D = D
        self.position: np.ndarray = _random_threshold_vector(D)
        self.velocity: np.ndarray = np.zeros(D, dtype=np.float64)
        self.personal_best: np.ndarray = self.position.copy()
        self.personal_best_fitness: float = -np.inf
        # Exemplar initialised to own personal best
        self.exemplar: np.ndarray = self.personal_best.copy()
        self.stagnation: int = 0  # consecutive non-improving iterations

    def evaluate(self, joint_hist: np.ndarray, q: float = 0.5) -> float:
        """Evaluate and update personal best; return raw fitness."""
        f = compute_2d_renyi_entropy(self.position, joint_hist, q)
        if f > self.personal_best_fitness:
            self.personal_best = self.position.copy()
            self.personal_best_fitness = f
            self.stagnation = 0
        else:
            self.stagnation += 1
        return f


# ===========================================================================
# 2.  EXEMPLAR CONSTRUCTION
# ===========================================================================

def _tournament_select(
    swarm: List[CLParticle],
    exclude_idx: int,
    rng: np.random.Generator,
) -> CLParticle:
    """Binary tournament selection from swarm (excluding particle *exclude_idx*)."""
    candidates = [j for j in range(len(swarm)) if j != exclude_idx]
    a, b = rng.choice(candidates, size=2, replace=False)
    if swarm[a].personal_best_fitness >= swarm[b].personal_best_fitness:
        return swarm[a]
    return swarm[b]


def _build_exemplar(
    i: int,
    swarm: List[CLParticle],
    pc: float,
    rng: np.random.Generator,
) -> np.ndarray:
    """Construct the composite exemplar f_i for particle i.

    For each dimension d:
      - With probability pc, learn from the personal best of a random
        competitor (chosen by binary tournament selection).
      - Otherwise, use the particle's own personal best.

    At least one dimension is forced to learn from a competitor so that
    the exemplar always changes (avoids stagnation at initialisation).
    """
    D = swarm[i].D
    exemplar = swarm[i].personal_best.copy().astype(np.float64)

    # Dimensions that will be updated from competitors
    learn_mask = rng.random(D) < pc
    if not learn_mask.any():
        # Force at least one dimension
        learn_mask[rng.integers(D)] = True

    for d in range(D):
        if learn_mask[d]:
            competitor = _tournament_select(swarm, i, rng)
            exemplar[d] = float(competitor.personal_best[d])

    return exemplar


# ===========================================================================
# 3.  CORE MCLPSO ALGORITHM
# ===========================================================================

def mclpso(
    joint_hist: np.ndarray,
    D: int,
    N: int = 50,
    FE_max: Optional[int] = None,
    omega: float = 0.729,
    c: float = 1.494,
    pc_min: float = 0.05,
    pc_max: float = 0.50,
    m: int = 7,
    q: float = 0.5,
    seed: Optional[int] = None,
    verbose: bool = False,
) -> Tuple[np.ndarray, float]:
    """Run the MCLPSO algorithm.

    Parameters
    ----------
    joint_hist : 2-D normalised joint histogram (256 x 256)
    D          : number of thresholds (problem dimension)
    N          : swarm size (default 50)
    FE_max     : max function evaluations; defaults to 10,000 * D
    omega      : inertia weight (default 0.729)
    c          : acceleration coefficient (default 1.494)
    pc_min     : minimum learning probability (default 0.05)
    pc_max     : maximum learning probability (default 0.50)
    m          : refresh gap — stagnation limit in iterations (default 7)
    q          : Renyi order parameter (default 0.5)
    seed       : optional random seed for reproducibility
    verbose    : print progress every 500 evaluations (default False)

    Returns
    -------
    (best_thresholds, best_fitness)
    """
    # ---- validation --------------------------------------------------------
    if joint_hist.ndim != 2 or joint_hist.shape[0] != joint_hist.shape[1]:
        raise ValueError("joint_hist must be a square 2-D array.")
    if D < 1:
        raise ValueError("D (number of thresholds) must be >= 1.")
    if N < 1:
        raise ValueError("N (swarm size) must be >= 1.")

    if FE_max is None:
        FE_max = 10_000 * D

    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)

    rng = np.random.default_rng(seed)

    # ---- learning probabilities (linearly spaced across the swarm) ---------
    # pc[i] increases from pc_min to pc_max so that the swarm contains both
    # conservative (low pc) and explorative (high pc) particles.
    if N > 1:
        pc_values = np.linspace(pc_min, pc_max, N)
    else:
        pc_values = np.array([pc_min])

    fe_used = 0

    # ---- initialise swarm --------------------------------------------------
    swarm: List[CLParticle] = [CLParticle(D) for _ in range(N)]
    for i, p in enumerate(swarm):
        f = compute_2d_renyi_entropy(p.position, joint_hist, q)
        fe_used += 1
        p.personal_best = p.position.copy()
        p.personal_best_fitness = f
        p.exemplar = p.personal_best.copy().astype(np.float64)

    best_idx = int(np.argmax([p.personal_best_fitness for p in swarm]))
    global_best: np.ndarray = swarm[best_idx].personal_best.copy()
    global_best_fitness: float = swarm[best_idx].personal_best_fitness

    last_verbose_fe = 0
    t = 0

    # ---- main loop ---------------------------------------------------------
    while fe_used < FE_max:
        t += 1
        for i, p in enumerate(swarm):
            if fe_used >= FE_max:
                break

            # -----------------------------------------------------------------
            # Refresh check: rebuild exemplar if stagnation >= m
            # -----------------------------------------------------------------
            if p.stagnation >= m:
                p.exemplar = _build_exemplar(i, swarm, pc_values[i], rng)
                p.stagnation = 0  # reset stagnation counter after refresh

            # -----------------------------------------------------------------
            # Velocity update (Comprehensive Learning version)
            #   v_i ← omega * v_i  +  c * r_i * (exemplar_i - x_i)
            # -----------------------------------------------------------------
            r = rng.uniform(0.0, 1.0, size=D)
            p.velocity = (
                omega * p.velocity
                + c * r * (p.exemplar.astype(np.float64) - p.position.astype(np.float64))
            )

            # Position update
            p.position = _clamp_and_sort(p.position.astype(np.float64) + p.velocity)

            # Evaluate and update personal / global best
            prev_pb_fitness = p.personal_best_fitness
            f = p.evaluate(joint_hist, q)
            fe_used += 1

            if f > global_best_fitness:
                global_best = p.position.copy()
                global_best_fitness = f

            # -----------------------------------------------------------------
            # If personal best improved, rebuild exemplar immediately so the
            # particle can share its new knowledge with others next iteration.
            # -----------------------------------------------------------------
            if p.personal_best_fitness > prev_pb_fitness:
                p.exemplar = _build_exemplar(i, swarm, pc_values[i], rng)

        if verbose and (fe_used - last_verbose_fe) >= 500:
            last_verbose_fe = fe_used
            print(
                f"  FE {fe_used:6d}/{FE_max}: fitness={global_best_fitness:.6f} "
                f"thresholds={global_best.tolist()}"
            )

    return global_best, global_best_fitness


# ===========================================================================
# 4.  SEGMENTATION PIPELINE
# ===========================================================================

def segment_mri_mclpso(
    image: np.ndarray,
    n_thresholds: int = 4,
    mclpso_kwargs: Optional[dict] = None,
    verbose: bool = False,
) -> Tuple[np.ndarray, np.ndarray, float]:
    """Full MRI segmentation pipeline using MCLPSO.

    Parameters
    ----------
    image        : grayscale MRI image (H x W).  uint8 preferred; float
                   arrays are normalised to [0, 255] uint8 automatically.
    n_thresholds : number of threshold levels D (produces D+1 segments)
    mclpso_kwargs: extra keyword arguments forwarded to mclpso()
    verbose      : whether to print progress

    Returns
    -------
    (thresholds, segmented_image, best_fitness)
      thresholds      : 1-D sorted int array of shape (D,)
      segmented_image : H x W uint8 label map (values 0 .. D)
      best_fitness    : final 2-D Renyi entropy value
    """
    if image.ndim != 2:
        raise ValueError(
            f"image must be a 2-D grayscale array; got shape {image.shape}. "
            "For colour images, convert to grayscale first."
        )
    if image.size == 0:
        raise ValueError("image must not be empty.")
    if n_thresholds < 1:
        raise ValueError("n_thresholds must be >= 1.")

    # Convert to uint8 if needed
    if image.dtype != np.uint8:
        img = image.astype(np.float32)
        lo, hi = img.min(), img.max()
        if hi > lo:
            img = (img - lo) / (hi - lo) * 255.0
        image = img.clip(0, 255).astype(np.uint8)

    if verbose:
        print("[MCLPSO] Computing nonlocal-means filtered image ...")
    filtered = nonlocal_means_filter(image)

    if verbose:
        print("[MCLPSO] Building 2-D joint histogram ...")
    joint_hist = build_joint_histogram(image, filtered, num_bins=_NBINS)

    if verbose:
        print(f"[MCLPSO] Running optimisation with D={n_thresholds} thresholds ...")
    kwargs = dict(mclpso_kwargs or {})
    kwargs.setdefault("verbose", verbose)
    thresholds, fitness = mclpso(joint_hist, D=n_thresholds, **kwargs)

    # Apply thresholds to produce integer label map
    boundaries = np.concatenate([[0], thresholds, [_NBINS]])
    segmented = np.zeros_like(image, dtype=np.uint8)
    for k in range(len(boundaries) - 1):
        lo, hi = int(boundaries[k]), int(boundaries[k + 1])
        segmented[(image >= lo) & (image < hi)] = k

    return thresholds, segmented, fitness


# ===========================================================================
# 5.  OPTIONAL: HEAD-TO-HEAD COMPARISON WITH HyPSO
# ===========================================================================

def compare_with_hypso(
    image: np.ndarray,
    n_thresholds: int = 3,
    fe_budget: int = 4_000,
    seed: int = 42,
    verbose: bool = True,
) -> dict:
    """Run both MCLPSO and HyPSO on *image* with the same budget and seed.

    Returns a dict with keys 'mclpso' and 'hypso', each containing
    a sub-dict with keys 'thresholds', 'fitness', and 'ssim'.

    Requires scikit-image for SSIM computation.
    """
    from hypso_mri_segmentation import segment_mri as hypso_segment

    results = {}

    for name, fn, kw in [
        (
            "mclpso",
            segment_mri_mclpso,
            {"mclpso_kwargs": {"N": 30, "FE_max": fe_budget, "seed": seed}},
        ),
        (
            "hypso",
            hypso_segment,
            {"hypso_kwargs": {"N": 30, "FE_max": fe_budget, "seed": seed}},
        ),
    ]:
        if verbose:
            print(f"\n{'='*50}")
            print(f"Running {name.upper()} ...")
            print(f"{'='*50}")
        thresholds, segmented, fitness = fn(
            image, n_thresholds=n_thresholds, verbose=verbose, **kw
        )
        try:
            ssim = compute_ssim(image, segmented)
        except ImportError:
            ssim = float("nan")
        results[name] = {
            "thresholds": thresholds.tolist(),
            "fitness": fitness,
            "ssim": ssim,
        }
        if verbose:
            print(f"  Thresholds : {thresholds.tolist()}")
            print(f"  Fitness    : {fitness:.6f}")
            print(f"  SSIM       : {ssim:.4f}" if not np.isnan(ssim) else "  SSIM: n/a")

    return results


# ===========================================================================
# 6.  COMMAND-LINE DEMO
# ===========================================================================

def _demo() -> None:
    """Quick self-test on a synthetic multi-region image."""
    print("=" * 60)
    print("MCLPSO MRI Segmentation — Demo")
    print("=" * 60)

    rng = np.random.default_rng(42)
    h, w = 128, 128
    img = np.full((h, w), 30, dtype=np.uint8)
    img[20:60, 20:60] = 90
    img[60:100, 60:100] = 150
    img[10:30, 90:110] = 200
    noise = rng.integers(-10, 10, size=(h, w))
    img = np.clip(img.astype(np.int32) + noise, 0, 255).astype(np.uint8)

    D = 3
    print(f"Image shape : {img.shape}, dtype: {img.dtype}")
    print(f"Thresholds  : D = {D}  →  {D + 1} segments")
    print()

    thresholds, segmented, fitness = segment_mri_mclpso(
        img,
        n_thresholds=D,
        mclpso_kwargs={
            "N": 20,
            "FE_max": 4_000,   # small budget for demo speed
            "seed": 1,
        },
        verbose=True,
    )

    print()
    print(f"Optimal thresholds : {thresholds.tolist()}")
    print(f"2D Renyi entropy   : {fitness:.6f}")
    print(f"Unique segments    : {np.unique(segmented).tolist()}")

    try:
        score = compute_ssim(img, segmented)
        print(f"SSIM               : {score:.4f}")
    except ImportError:
        print("SSIM: scikit-image not available, skipping.")

    # ------------------------------------------------------------------
    # Optional head-to-head comparison with HyPSO
    # ------------------------------------------------------------------
    print()
    print("Running head-to-head comparison with HyPSO ...")
    try:
        results = compare_with_hypso(img, n_thresholds=D, fe_budget=4_000, seed=1)
        print()
        print("Summary")
        print("-" * 40)
        for algo, r in results.items():
            ssim_str = f"{r['ssim']:.4f}" if not np.isnan(r["ssim"]) else "n/a"
            print(
                f"  {algo.upper():8s}  fitness={r['fitness']:.6f}  "
                f"SSIM={ssim_str}  t={r['thresholds']}"
            )
    except Exception as exc:  # noqa: BLE001
        print(f"  (comparison skipped: {exc})")

    print()
    print("Demo completed successfully.")


if __name__ == "__main__":
    _demo()
